In [7]:
import requests
import json
import re
import pandas as pd
import time
import pickle
import itertools

def call_chat_api(query):
    url = "http://localhost/v1/chat-messages"
    headers = {
        # Replace TOKEN with the agent token.
        "Authorization": "Bearer TOKEN",
        "Content-Type": "application/json"
    }
    payload = {
        "inputs": {},
        "query": query,
        "response_mode": "blocking",
        "user": "abc-123"
    }
    response = requests.post(url, headers=headers, json=payload)
    if response.status_code == 200:
        return response.json()
    else:
        return f"Error: {response.status_code}, {response.text}"

In [8]:
query_template = """
For the company: "{company_name}"
Context:
- Identify key decision-makers at a specified company. For companies with fewer than 10,000 employees, provide the full executive team (CEO, CFO, COO, Chief Strategy Officer, etc.) along with any dedicated corporate development leaders. Use publicly available sources such as the company's leadership page, press releases, reputable business directories (e.g., Crunchbase, PitchBook, Bloomberg), and LinkedIn profiles to gather names, job titles, company size, and source links.
Role:
- You are an expert business researcher and data analyst specializing in corporate intelligence and market research. Your approach is methodical and strategic, ensuring data accuracy by filtering out outdated information and cross-verifying with multiple authoritative sources.
Action:
Search Scope:
- Identify key executives and corporate development leaders (e.g., VP/Director/Head of Corporate Development, M&A, or Strategy & Business Development leads) using multiple sources.
- If the company has fewer than 10,000 employees, also retrieve the full executive team, including but not limited to CEO, CFO, COO, CSO, and any additional C-level roles.
- Explicitly search LinkedIn to supplement and cross-check information from the company's leadership page and other public directories.
Data Sources:
- Primary: LinkedIn profiles (for current and comprehensive leadership details).
- Secondary: Company leadership pages, press releases, and respected business directories.
Compile a structured list that includes:
- Company name
- Company domain
- Companyy size (confirm whether it's <10,000 employees)
- Job title
- Full name
- First name
- Email
- Linkedin
- Source link (LinkedIn profile, company website, or another reliable source)
Additional Notes:
- When only one result appears from the company's website, make sure to cross-check with LinkedIn to identify any additional executives or corporate development leaders.
- Given that executive teams and roles can change quickly, confirm the information with multiple sources.
Present the results sorted in descending order of seniority. If a direct match (e.g., VP of Corporate Development) isn't found, include the closest alternative with a brief explanation.
Return ONLY a JSON array with objects for each executive:
[
 {{
   "company_name": "",
   "company_domain": "",
   "company_size": "",
   "job_title": "",
   "fullname": "",
   "first_name": "",
   "email": "",
   "linkedin": "",
   "source_link": ""
 }}
]
Present the results sorted in descending order of seniority. Do not include any text outside this JSON structure.
"""

In [9]:
companies = [
    "Walmart",
    "Amazon",
    "Apple",
    "UnitedHealth Group",
    "Berkshire Hathaway",
    "CVS Health",
    "Exxon Mobil",
    "Alphabet",
    "McKesson",
    "Cencora",
    "Costco",
    "JPMorgan Chase",
    "Microsoft",
    "Cardinal Health",
    "Chevron",
    "Cigna Group",
    "Ford Motor",
    "Bank of America",
    "General Motors",
    "Elevance Health",
    "Citigroup",
    "Centene",
    "Home Depot",
    "Marathon Petroleum",
    "Kroger",
    "Phillips 66",
    "Fannie Mae",
    "Walgreens Boots Alliance",
    "Valero Energy",
    "Meta Platforms",
    "Verizon Communications",
    "AT&T",
    "Comcast",
    "Wells Fargo",
    "Goldman Sachs Group",
    "Freddie Mac",
    "Target",
    "Humana",
    "State Farm Insurance",
    "Tesla",
    "Morgan Stanley",
    "Johnson & Johnson",
    "Archer Daniels Midland",
    "PepsiCo",
    "United Parcel Service",
    "FedEx",
    "Walt Disney",
    "Dell Technologies",
    "Lowe's",
    "Procter & Gamble",
]

In [75]:
results = []
for c in companies:
    query = query_template.format(company_name=c)
    print(c)
    print(query.split("\n")[1])
    print("-----")
    time.sleep(1)
    result = call_chat_api(query)
    results.append(result)

Amazon
For the company: "Amazon"
-----
Apple
For the company: "Apple"
-----
UnitedHealth Group
For the company: "UnitedHealth Group"
-----
Berkshire Hathaway
For the company: "Berkshire Hathaway"
-----
CVS Health
For the company: "CVS Health"
-----
Exxon Mobil
For the company: "Exxon Mobil"
-----
Alphabet
For the company: "Alphabet"
-----
McKesson
For the company: "McKesson"
-----
Cencora
For the company: "Cencora"
-----
Costco
For the company: "Costco"
-----
JPMorgan Chase
For the company: "JPMorgan Chase"
-----
Microsoft
For the company: "Microsoft"
-----
Cardinal Health
For the company: "Cardinal Health"
-----
Chevron
For the company: "Chevron"
-----
Cigna Group
For the company: "Cigna Group"
-----
Ford Motor
For the company: "Ford Motor"
-----
Bank of America
For the company: "Bank of America"
-----
General Motors
For the company: "General Motors"
-----
Elevance Health
For the company: "Elevance Health"
-----
Citigroup
For the company: "Citigroup"
-----
Centene
For the company: "Centene"
-----
Home Depot
For the company: "Home Depot"
-----
Marathon Petroleum
For the company: "Marathon Petroleum"
-----
Kroger
For the company: "Kroger"
-----
Phillips 66
For the company: "Phillips 66"
-----
Fannie Mae
For the company: "Fannie Mae"
-----
Walgreens Boots Alliance
For the company: "Walgreens Boots Alliance"
-----
Valero Energy
For the company: "Valero Energy"
-----
Meta Platforms
For the company: "Meta Platforms"
-----
Verizon Communications
For the company: "Verizon Communications"
-----
AT&T
For the company: "AT&T"
-----
Comcast
For the company: "Comcast"
-----
Wells Fargo
For the company: "Wells Fargo"
-----
Goldman Sachs Group
For the company: "Goldman Sachs Group"
-----
Freddie Mac
For the company: "Freddie Mac"
-----
Target
For the company: "Target"
-----
Humana
For the company: "Humana"
-----
State Farm Insurance
For the company: "State Farm Insurance"
-----
Tesla
For the company: "Tesla"
-----
Morgan Stanley
For the company: "Morgan Stanley"
-----
Johnson & Johnson
For the company: "Johnson & Johnson"
-----
Archer Daniels Midland
For the company: "Archer Daniels Midland"
-----
PepsiCo
For the company: "PepsiCo"
-----
United Parcel Service
For the company: "United Parcel Service"
-----
FedEx
For the company: "FedEx"
-----
Walt Disney
For the company: "Walt Disney"
-----
Dell Technologies
For the company: "Dell Technologies"
-----
Lowe's
For the company: "Lowe's"
-----
Procter & Gamble
For the company: "Procter & Gamble"
-----

In [76]:
with open('data.pkl', 'wb') as file:
    pickle.dump(results, file)

In [77]:
result

{'event': 'message',
 'task_id': '7fe5f640-dd3f-4b95-a247-6bcc605d5628',
 'id': 'def36fef-79c1-420f-b227-14d907e02763',
 'message_id': 'def36fef-79c1-420f-b227-14d907e02763',
 'conversation_id': 'c39acf37-67fd-46b7-a0c1-126ff37d43a2',
 'mode': 'advanced-chat',
 'answer': '1/Noneth search executed.\n2/Noneth search executed.\n3/Noneth search executed.\n\n```json\n[\n  {\n    "company_name": "Procter & Gamble",\n    "company_domain": "pg.com",\n    "company_size": "101,000",\n    "job_title": "Chairman of the Board, President and Chief Executive Officer",\n    "fullname": "Jon R. Moeller",\n    "first_name": "Jon",\n    "email": "moeller.jr@pg.com",\n    "linkedin": "https://www.linkedin.com/in/jon-moeller-pg",\n    "source_link": "https://executive-emails.com/l-p/proctor-gamble/"\n  },\n  {\n    "company_name": "Procter & Gamble",\n    "company_domain": "pg.com",\n    "company_size": "101,000",\n    "job_title": "Chief Operating Officer",\n    "fullname": "Shailesh G. Jejurikar",\n    "first_name": "Shailesh",\n    "email": "Jejurikar.sg@pg.com",\n    "linkedin": "",\n    "source_link": "https://executive-emails.com/l-p/proctor-gamble/"\n  },\n  {\n    "company_name": "Procter & Gamble",\n    "company_domain": "pg.com",\n    "company_size": "101,000",\n    "job_title": "Chief Executive Officer – Beauty",\n    "fullname": "R. Alexandra Keith",\n    "first_name": "R. Alexandra",\n    "email": "",\n    "linkedin": "https://us.pg.com/leadership-team/alexandra-keith/",\n    "source_link": "https://us.pg.com/leadership-team/alexandra-keith/"\n  },\n  {\n    "company_name": "Procter & Gamble",\n    "company_domain": "pg.com",\n    "company_size": "101,000",\n    "job_title": "Chief Executive Officer, Global Grooming Business",\n    "fullname": "Gary Coombe",\n    "first_name": "Gary",\n    "email": "",\n    "linkedin": "https://www.linkedin.com/in/garyacoombe",\n    "source_link": "https://www.linkedin.com/in/garyacoombe"\n  },\n  {\n    "company_name": "Procter & Gamble",\n    "company_domain": "pg.com",\n    "company_size": "101,000",\n    "job_title": "Chief Executive Officer, Fabric & Home Care",\n    "fullname": "Sundar G. Raman",\n    "first_name": "Sundar",\n    "email": "",\n    "linkedin": "https://us.pg.com/leadership-team/sundar-raman/",\n    "source_link": "https://us.pg.com/leadership-team/sundar-raman/"\n  },\n  {\n    "company_name": "Procter & Gamble",\n    "company_domain": "pg.com",\n    "company_size": "101,000",\n    "job_title": "Chief Research, Development, and Innovation Officer",\n    "fullname": "Victor Aguilar",\n    "first_name": "Victor",\n    "email": "",\n    "linkedin": "",\n    "source_link": "https://pgresearchdevelop.com/team/"\n  },\n  {\n    "company_name": "Procter & Gamble",\n    "company_domain": "pg.com",\n    "company_size": "101,000",\n    "job_title": "President – Home Care and P&G Professional",\n    "fullname": "Juliana Azevedo",\n    "first_name": "Juliana",\n    "email": "",\n    "linkedin": "",\n    "source_link": "https://us.pg.com/annualreport2022/company_leadership.pdf"\n  },\n  {\n    "company_name": "Procter & Gamble",\n    "company_domain": "pg.com",\n    "company_size": "101,000",\n    "job_title": "President – Personal Care",\n    "fullname": "Freddy Bharucha",\n    "first_name": "Freddy",\n    "email": "",\n    "linkedin": "",\n    "source_link": "https://us.pg.com/leadership-team/"\n  },\n  {\n    "company_name": "Procter & Gamble",\n    "company_domain": "pg.com",\n    "company_size": "101,000",\n    "job_title": "President – Family Care",\n    "fullname": "Eric Breissinger",\n    "first_name": "Eric",\n    "email": "",\n    "linkedin": "",\n    "source_link": "https://us.pg.com/leadership-team/"\n  },\n  {\n    "company_name": "Procter & Gamble",\n    "company_domain": "pg.com",\n    "company_size": "101,000",\n    "job_title": "President – Global Business Services",\n    "fullname": "April Cielica",\n    "first_name": "April",\n    "email": "",\n    "linkedin": "",\n    "source_link": "https://us.pg.com/leadership-team/"\n  },\n  {\n    "company_name": "Procter & Gamble",\n    "company_domain": "pg.com",\n    "company_size": "101,000",\n    "job_title": "Chief Information Officer",\n    "fullname": "Seth Cohen",\n    "first_name": "Seth",\n    "email": "",\n    "linkedin": "",\n    "source_link": "https://us.pg.com/leadership-team/"\n  },\n  {\n    "company_name": "Procter & Gamble",\n    "company_domain": "pg.com",\n    "company_size": "101,000",\n    "job_title": "Chief Equality and Inclusion Officer",\n    "fullname": "Kristine Decker",\n    "first_name": "Kristine",\n    "email": "",\n    "linkedin": "",\n    "source_link": "https://us.pg.com/leadership-team/"\n  },\n  {\n    "company_name": "Procter & Gamble",\n    "company_domain": "pg.com",\n    "company_size": "101,000",\n    "job_title": "Vice President, Corporate Development",\n    "fullname": "Bala Purushothaman",\n    "first_name": "Bala",\n    "email": "",\n    "linkedin": "",\n    "source_link": "https://craft.co/procter-gamble/executives"\n  },\n  {\n    "company_name": "Procter & Gamble",\n    "company_domain": "pg.com",\n    "company_size": "101,000",\n    "job_title": "Vice President, M&A",\n    "fullname": "Luc Reynaert",\n    "first_name": "Luc",\n    "email": "",\n    "linkedin": "",\n    "source_link": "https://craft.co/procter-gamble/executives"\n  },\n  {\n    "company_name": "Procter & Gamble",\n    "company_domain": "pg.com",\n    "company_size": "101,000",\n    "job_title": "Vice President, Strategy & Business Development",\n    "fullname": "Kirti Singh",\n    "first_name": "Kirti",\n    "email": "",\n    "linkedin": "",\n    "source_link": "https://craft.co/procter-gamble/executives"\n  },\n  {\n    "company_name": "Procter & Gamble",\n    "company_domain": "pg.com",\n    "company_size": "101,000",\n    "job_title": "Vice President, Corporate Development",\n    "fullname": "Andre Schulten",\n    "first_name": "Andre",\n    "email": "",\n    "linkedin": "",\n    "source_link": "https://craft.co/procter-gamble/executives"\n  }\n]\n```',
 'metadata': {'usage': {'prompt_tokens': 7196,
   'prompt_unit_price': '3.00',
   'prompt_price_unit': '0.000001',
   'prompt_price': '0.0215880',
   'completion_tokens': 3644,
   'completion_unit_price': '12.00',
   'completion_price_unit': '0.000001',
   'completion_price': '0.0437280',
   'total_tokens': 10840,
   'total_price': '0.0653160',
   'currency': 'USD',
   'latency': 22.865864719002275}},
 'created_at': 1740547174}

In [78]:
result['answer']

'1/Noneth search executed.\n2/Noneth search executed.\n3/Noneth search executed.\n\n```json\n[\n  {\n    "company_name": "Procter & Gamble",\n    "company_domain": "pg.com",\n    "company_size": "101,000",\n    "job_title": "Chairman of the Board, President and Chief Executive Officer",\n    "fullname": "Jon R. Moeller",\n    "first_name": "Jon",\n    "email": "moeller.jr@pg.com",\n    "linkedin": "https://www.linkedin.com/in/jon-moeller-pg",\n    "source_link": "https://executive-emails.com/l-p/proctor-gamble/"\n  },\n  {\n    "company_name": "Procter & Gamble",\n    "company_domain": "pg.com",\n    "company_size": "101,000",\n    "job_title": "Chief Operating Officer",\n    "fullname": "Shailesh G. Jejurikar",\n    "first_name": "Shailesh",\n    "email": "Jejurikar.sg@pg.com",\n    "linkedin": "",\n    "source_link": "https://executive-emails.com/l-p/proctor-gamble/"\n  },\n  {\n    "company_name": "Procter & Gamble",\n    "company_domain": "pg.com",\n    "company_size": "101,000",\n    "job_title": "Chief Executive Officer – Beauty",\n    "fullname": "R. Alexandra Keith",\n    "first_name": "R. Alexandra",\n    "email": "",\n    "linkedin": "https://us.pg.com/leadership-team/alexandra-keith/",\n    "source_link": "https://us.pg.com/leadership-team/alexandra-keith/"\n  },\n  {\n    "company_name": "Procter & Gamble",\n    "company_domain": "pg.com",\n    "company_size": "101,000",\n    "job_title": "Chief Executive Officer, Global Grooming Business",\n    "fullname": "Gary Coombe",\n    "first_name": "Gary",\n    "email": "",\n    "linkedin": "https://www.linkedin.com/in/garyacoombe",\n    "source_link": "https://www.linkedin.com/in/garyacoombe"\n  },\n  {\n    "company_name": "Procter & Gamble",\n    "company_domain": "pg.com",\n    "company_size": "101,000",\n    "job_title": "Chief Executive Officer, Fabric & Home Care",\n    "fullname": "Sundar G. Raman",\n    "first_name": "Sundar",\n    "email": "",\n    "linkedin": "https://us.pg.com/leadership-team/sundar-raman/",\n    "source_link": "https://us.pg.com/leadership-team/sundar-raman/"\n  },\n  {\n    "company_name": "Procter & Gamble",\n    "company_domain": "pg.com",\n    "company_size": "101,000",\n    "job_title": "Chief Research, Development, and Innovation Officer",\n    "fullname": "Victor Aguilar",\n    "first_name": "Victor",\n    "email": "",\n    "linkedin": "",\n    "source_link": "https://pgresearchdevelop.com/team/"\n  },\n  {\n    "company_name": "Procter & Gamble",\n    "company_domain": "pg.com",\n    "company_size": "101,000",\n    "job_title": "President – Home Care and P&G Professional",\n    "fullname": "Juliana Azevedo",\n    "first_name": "Juliana",\n    "email": "",\n    "linkedin": "",\n    "source_link": "https://us.pg.com/annualreport2022/company_leadership.pdf"\n  },\n  {\n    "company_name": "Procter & Gamble",\n    "company_domain": "pg.com",\n    "company_size": "101,000",\n    "job_title": "President – Personal Care",\n    "fullname": "Freddy Bharucha",\n    "first_name": "Freddy",\n    "email": "",\n    "linkedin": "",\n    "source_link": "https://us.pg.com/leadership-team/"\n  },\n  {\n    "company_name": "Procter & Gamble",\n    "company_domain": "pg.com",\n    "company_size": "101,000",\n    "job_title": "President – Family Care",\n    "fullname": "Eric Breissinger",\n    "first_name": "Eric",\n    "email": "",\n    "linkedin": "",\n    "source_link": "https://us.pg.com/leadership-team/"\n  },\n  {\n    "company_name": "Procter & Gamble",\n    "company_domain": "pg.com",\n    "company_size": "101,000",\n    "job_title": "President – Global Business Services",\n    "fullname": "April Cielica",\n    "first_name": "April",\n    "email": "",\n    "linkedin": "",\n    "source_link": "https://us.pg.com/leadership-team/"\n  },\n  {\n    "company_name": "Procter & Gamble",\n    "company_domain": "pg.com",\n    "company_size": "101,000",\n    "job_title": "Chief Information Officer",\n    "fullname": "Seth Cohen",\n    "first_name": "Seth",\n    "email": "",\n    "linkedin": "",\n    "source_link": "https://us.pg.com/leadership-team/"\n  },\n  {\n    "company_name": "Procter & Gamble",\n    "company_domain": "pg.com",\n    "company_size": "101,000",\n    "job_title": "Chief Equality and Inclusion Officer",\n    "fullname": "Kristine Decker",\n    "first_name": "Kristine",\n    "email": "",\n    "linkedin": "",\n    "source_link": "https://us.pg.com/leadership-team/"\n  },\n  {\n    "company_name": "Procter & Gamble",\n    "company_domain": "pg.com",\n    "company_size": "101,000",\n    "job_title": "Vice President, Corporate Development",\n    "fullname": "Bala Purushothaman",\n    "first_name": "Bala",\n    "email": "",\n    "linkedin": "",\n    "source_link": "https://craft.co/procter-gamble/executives"\n  },\n  {\n    "company_name": "Procter & Gamble",\n    "company_domain": "pg.com",\n    "company_size": "101,000",\n    "job_title": "Vice President, M&A",\n    "fullname": "Luc Reynaert",\n    "first_name": "Luc",\n    "email": "",\n    "linkedin": "",\n    "source_link": "https://craft.co/procter-gamble/executives"\n  },\n  {\n    "company_name": "Procter & Gamble",\n    "company_domain": "pg.com",\n    "company_size": "101,000",\n    "job_title": "Vice President, Strategy & Business Development",\n    "fullname": "Kirti Singh",\n    "first_name": "Kirti",\n    "email": "",\n    "linkedin": "",\n    "source_link": "https://craft.co/procter-gamble/executives"\n  },\n  {\n    "company_name": "Procter & Gamble",\n    "company_domain": "pg.com",\n    "company_size": "101,000",\n    "job_title": "Vice President, Corporate Development",\n    "fullname": "Andre Schulten",\n    "first_name": "Andre",\n    "email": "",\n    "linkedin": "",\n    "source_link": "https://craft.co/procter-gamble/executives"\n  }\n]\n```'

In [79]:
def parse_data(input_text):
    """
    Parse the Scale AI leadership data from the given text.
    This extracts the JSON array from the code block in the text.
    """
    # Find JSON content between ```json and ``` markers
    json_pattern = r'```json\s*([\s\S]*?)\s*```'
    json_match = re.search(json_pattern, input_text)
    if not json_match:
        print("Could not find JSON content between ```json and ``` markers")
        return None
    json_str = json_match.group(1)
    try:
        data = json.loads(json_str)
        return data
    except json.JSONDecodeError as e:
        print(f"Error parsing JSON: {e}")
        return None

In [80]:
parse_data(result['answer'])

[{'company_name': 'Procter & Gamble',
  'company_domain': 'pg.com',
  'company_size': '101,000',
  'job_title': 'Chairman of the Board, President and Chief Executive Officer',
  'fullname': 'Jon R. Moeller',
  'first_name': 'Jon',
  'email': 'moeller.jr@pg.com',
  'linkedin': 'https://www.linkedin.com/in/jon-moeller-pg',
  'source_link': 'https://executive-emails.com/l-p/proctor-gamble/'},
 {'company_name': 'Procter & Gamble',
  'company_domain': 'pg.com',
  'company_size': '101,000',
  'job_title': 'Chief Operating Officer',
  'fullname': 'Shailesh G. Jejurikar',
  'first_name': 'Shailesh',
  'email': 'Jejurikar.sg@pg.com',
  'linkedin': '',
  'source_link': 'https://executive-emails.com/l-p/proctor-gamble/'},
 {'company_name': 'Procter & Gamble',
  'company_domain': 'pg.com',
  'company_size': '101,000',
  'job_title': 'Chief Executive Officer – Beauty',
  'fullname': 'R. Alexandra Keith',
  'first_name': 'R. Alexandra',
  'email': '',
  'linkedin': 'https://us.pg.com/leadership-team/alexandra-keith/',
  'source_link': 'https://us.pg.com/leadership-team/alexandra-keith/'},
 {'company_name': 'Procter & Gamble',
  'company_domain': 'pg.com',
  'company_size': '101,000',
  'job_title': 'Chief Executive Officer, Global Grooming Business',
  'fullname': 'Gary Coombe',
  'first_name': 'Gary',
  'email': '',
  'linkedin': 'https://www.linkedin.com/in/garyacoombe',
  'source_link': 'https://www.linkedin.com/in/garyacoombe'},
 {'company_name': 'Procter & Gamble',
  'company_domain': 'pg.com',
  'company_size': '101,000',
  'job_title': 'Chief Executive Officer, Fabric & Home Care',
  'fullname': 'Sundar G. Raman',
  'first_name': 'Sundar',
  'email': '',
  'linkedin': 'https://us.pg.com/leadership-team/sundar-raman/',
  'source_link': 'https://us.pg.com/leadership-team/sundar-raman/'},
 {'company_name': 'Procter & Gamble',
  'company_domain': 'pg.com',
  'company_size': '101,000',
  'job_title': 'Chief Research, Development, and Innovation Officer',
  'fullname': 'Victor Aguilar',
  'first_name': 'Victor',
  'email': '',
  'linkedin': '',
  'source_link': 'https://pgresearchdevelop.com/team/'},
 {'company_name': 'Procter & Gamble',
  'company_domain': 'pg.com',
  'company_size': '101,000',
  'job_title': 'President – Home Care and P&G Professional',
  'fullname': 'Juliana Azevedo',
  'first_name': 'Juliana',
  'email': '',
  'linkedin': '',
  'source_link': 'https://us.pg.com/annualreport2022/company_leadership.pdf'},
 {'company_name': 'Procter & Gamble',
  'company_domain': 'pg.com',
  'company_size': '101,000',
  'job_title': 'President – Personal Care',
  'fullname': 'Freddy Bharucha',
  'first_name': 'Freddy',
  'email': '',
  'linkedin': '',
  'source_link': 'https://us.pg.com/leadership-team/'},
 {'company_name': 'Procter & Gamble',
  'company_domain': 'pg.com',
  'company_size': '101,000',
  'job_title': 'President – Family Care',
  'fullname': 'Eric Breissinger',
  'first_name': 'Eric',
  'email': '',
  'linkedin': '',
  'source_link': 'https://us.pg.com/leadership-team/'},
 {'company_name': 'Procter & Gamble',
  'company_domain': 'pg.com',
  'company_size': '101,000',
  'job_title': 'President – Global Business Services',
  'fullname': 'April Cielica',
  'first_name': 'April',
  'email': '',
  'linkedin': '',
  'source_link': 'https://us.pg.com/leadership-team/'},
 {'company_name': 'Procter & Gamble',
  'company_domain': 'pg.com',
  'company_size': '101,000',
  'job_title': 'Chief Information Officer',
  'fullname': 'Seth Cohen',
  'first_name': 'Seth',
  'email': '',
  'linkedin': '',
  'source_link': 'https://us.pg.com/leadership-team/'},
 {'company_name': 'Procter & Gamble',
  'company_domain': 'pg.com',
  'company_size': '101,000',
  'job_title': 'Chief Equality and Inclusion Officer',
  'fullname': 'Kristine Decker',
  'first_name': 'Kristine',
  'email': '',
  'linkedin': '',
  'source_link': 'https://us.pg.com/leadership-team/'},
 {'company_name': 'Procter & Gamble',
  'company_domain': 'pg.com',
  'company_size': '101,000',
  'job_title': 'Vice President, Corporate Development',
  'fullname': 'Bala Purushothaman',
  'first_name': 'Bala',
  'email': '',
  'linkedin': '',
  'source_link': 'https://craft.co/procter-gamble/executives'},
 {'company_name': 'Procter & Gamble',
  'company_domain': 'pg.com',
  'company_size': '101,000',
  'job_title': 'Vice President, M&A',
  'fullname': 'Luc Reynaert',
  'first_name': 'Luc',
  'email': '',
  'linkedin': '',
  'source_link': 'https://craft.co/procter-gamble/executives'},
 {'company_name': 'Procter & Gamble',
  'company_domain': 'pg.com',
  'company_size': '101,000',
  'job_title': 'Vice President, Strategy & Business Development',
  'fullname': 'Kirti Singh',
  'first_name': 'Kirti',
  'email': '',
  'linkedin': '',
  'source_link': 'https://craft.co/procter-gamble/executives'},
 {'company_name': 'Procter & Gamble',
  'company_domain': 'pg.com',
  'company_size': '101,000',
  'job_title': 'Vice President, Corporate Development',
  'fullname': 'Andre Schulten',
  'first_name': 'Andre',
  'email': '',
  'linkedin': '',
  'source_link': 'https://craft.co/procter-gamble/executives'}]

In [95]:
json_list = []
for a in results:
    try:
        json_obj = parse_data(a['answer'])
        json_list.append(json_obj)
    except:
        print(a)

Error: 400, {"code": "invalid_param", "message": "Run failed: error: operation not permitted\n", "status": 400}

Could not find JSON content between ```json and ``` markers
Error: 400, {"code": "invalid_param", "message": "Run failed: error: operation not permitted\n", "status": 400}

Error: 400, {"code": "invalid_param", "message": "Run failed: error: operation not permitted\n", "status": 400}

Could not find JSON content between ```json and ``` markers
Could not find JSON content between ```json and ``` markers

In [120]:
json_list[1]

[{'company_name': 'Amazon',
  'company_domain': 'amazon.com',
  'company_size': '10,001+ employees',
  'job_title': 'President and CEO',
  'fullname': 'Andy Jassy',
  'first_name': 'Andy',
  'email': '',
  'linkedin': 'https://www.linkedin.com/in/andy-jassy',
  'source_link': 'https://ir.aboutamazon.com/officers-and-directors/default.aspx'},
 {'company_name': 'Amazon',
  'company_domain': 'amazon.com',
  'company_size': '10,001+ employees',
  'job_title': 'CEO, Worldwide Amazon Stores',
  'fullname': 'Doug Herrington',
  'first_name': 'Doug',
  'email': '',
  'linkedin': 'https://www.linkedin.com/in/doug-herrington',
  'source_link': 'https://www.linkedin.com/in/doug-herrington'},
 {'company_name': 'Amazon',
  'company_domain': 'amazon.com',
  'company_size': '10,001+ employees',
  'job_title': 'Senior Vice President, Amazon Video and Studios',
  'fullname': 'Mike Hopkins',
  'first_name': 'Mike',
  'email': '',
  'linkedin': '',
  'source_link': 'https://www.aboutamazon.com/news/workplace/amazon-s-team-members'},
 {'company_name': 'Amazon',
  'company_domain': 'amazon.com',
  'company_size': '10,001+ employees',
  'job_title': 'Senior Vice President, Amazon Health Services',
  'fullname': 'Neil Lindsay',
  'first_name': 'Neil',
  'email': '',
  'linkedin': '',
  'source_link': 'https://www.linkedin.com/in/neil-lindsay'},
 {'company_name': 'Amazon',
  'company_domain': 'amazon.com',
  'company_size': '10,001+ employees',
  'job_title': 'Vice President, Worldwide Corporate Development',
  'fullname': 'Dan Grossman',
  'first_name': 'Dan',
  'email': '',
  'linkedin': 'https://www.linkedin.com/in/dangrossman',
  'source_link': 'https://www.linkedin.com/in/dangrossman'},
 {'company_name': 'Amazon',
  'company_domain': 'amazon.com',
  'company_size': '10,001+ employees',
  'job_title': 'Corporate Development Leader',
  'fullname': 'Kareem Akhtar',
  'first_name': 'Kareem',
  'email': '',
  'linkedin': 'https://www.linkedin.com/in/kareem-akhtar-688756',
  'source_link': 'https://www.linkedin.com/in/kareem-akhtar-688756'},
 {'company_name': 'Amazon',
  'company_domain': 'amazon.com',
  'company_size': '10,001+ employees',
  'job_title': 'Corporate Development',
  'fullname': 'Neeraj Datta',
  'first_name': 'Neeraj',
  'email': '',
  'linkedin': 'https://www.linkedin.com/in/neeraj-datta-6173a625',
  'source_link': 'https://www.linkedin.com/in/neeraj-datta-6173a625'},
 {'company_name': 'Amazon',
  'company_domain': 'amazon.com',
  'company_size': '10,001+ employees',
  'job_title': 'Corporate Development',
  'fullname': 'Ryan Hunt',
  'first_name': 'Ryan',
  'email': '',
  'linkedin': 'https://www.linkedin.com/in/ryanthomashunt',
  'source_link': 'https://www.linkedin.com/in/ryanthomashunt'},
 {'company_name': 'Amazon',
  'company_domain': 'amazon.com',
  'company_size': '10,001+ employees',
  'job_title': 'Corporate Development',
  'fullname': 'Adam Harrell',
  'first_name': 'Adam',
  'email': '',
  'linkedin': 'https://www.linkedin.com/in/adam-harrell-70241895',
  'source_link': 'https://www.linkedin.com/in/adam-harrell-70241895'},
 {'company_name': 'Amazon',
  'company_domain': 'amazon.com',
  'company_size': '10,001+ employees',
  'job_title': "Member of Amazon's Senior Leadership Team",
  'fullname': 'Christine B.',
  'first_name': 'Christine',
  'email': '',
  'linkedin': 'https://www.linkedin.com/in/christine-b-28714823',
  'source_link': 'https://www.linkedin.com/in/christine-b-28714823'},
 {'company_name': 'Amazon',
  'company_domain': 'amazon.com',
  'company_size': '10,001+ employees',
  'job_title': 'Senior Vice President of International Consumer Business',
  'fullname': 'Diego Piacentini',
  'first_name': 'Diego',
  'email': '',
  'linkedin': '',
  'source_link': 'https://www.comparably.com/companies/amazon/executive-team'},
 {'company_name': 'Amazon',
  'company_domain': 'amazon.com',
  'company_size': '10,001+ employees',
  'job_title': 'Senior Vice President of International Consumer',
  'fullname': 'Russ Grandinetti',
  'first_name': 'Russ',
  'email': '',
  'linkedin': '',
  'source_link': 'https://www.comparably.com/companies/amazon/executive-team'}]

In [111]:
flattened = []
for item in json_list:
    if item is None:
        # Skip None values
        continue
    elif hasattr(item, '__iter__') and not isinstance(item, (str, dict)):
        # If item is iterable (but not a string or dictionary)
        flattened.extend(item)
    else:
        # For non-iterable items, add them directly
        flattened.append(item)

In [122]:
len(flattened)

454

In [121]:
flattened[1]

{'company_name': 'Walmart',
 'company_domain': 'walmart.com',
 'company_size': '10,001+ employees',
 'job_title': 'President and CEO, Walmart U.S.',
 'fullname': 'John Furner',
 'first_name': 'John',
 'email': '',
 'linkedin': 'https://www.linkedin.com/in/furner',
 'source_link': 'https://www.linkedin.com/in/furner'}

In [113]:
df = pd.DataFrame(flattened)

In [114]:
df.shape

(454, 9)

In [115]:
df.head(n=7)

,company_name,company_domain,company_size,job_title,fullname,first_name,email,linkedin,source_link
0,Walmart,walmart.com,"10,001+ employees",CEO and President,C. Douglas McMillon,Douglas,,,https://corporate.walmart.com/about/leadership
1,Walmart,walmart.com,"10,001+ employees","President and CEO, Walmart U.S.",John Furner,John,,https://www.linkedin.com/in/furner,https://www.linkedin.com/in/furner
2,Walmart,walmart.com,"10,001+ employees","President and CEO, Walmart International",Kathryn McLay,Kathryn,,https://www.linkedin.com/in/kathmclay,https://corporate.walmart.com/about/leadership...
3,Walmart,walmart.com,"10,001+ employees",Executive Vice President and Chief Growth Offi...,Chris Farrell,Chris,,,https://corporate.walmart.com/about/leadership
4,Walmart,walmart.com,"10,001+ employees",Executive Vice President and Chief Sustainabil...,David Guggina,David,,,https://corporate.walmart.com/about/leadership
5,Walmart,walmart.com,"10,001+ employees",Executive Vice President and Chief Financial O...,Dwayne Milum,Dwayne,,,https://corporate.walmart.com/about/leadership
6,Walmart,walmart.com,"10,001+ employees",Executive Vice President and Chief Operating O...,Todd Sears,Todd,,,https://corporate.walmart.com/about/leadership

In [116]:
df.tail()

,company_name,company_domain,company_size,job_title,fullname,first_name,email,linkedin,source_link
449,Procter & Gamble,pg.com,"101,000",Chief Equality and Inclusion Officer,Kristine Decker,Kristine,,,https://us.pg.com/leadership-team/
450,Procter & Gamble,pg.com,"101,000","Vice President, Corporate Development",Bala Purushothaman,Bala,,,https://craft.co/procter-gamble/executives
451,Procter & Gamble,pg.com,"101,000","Vice President, M&A",Luc Reynaert,Luc,,,https://craft.co/procter-gamble/executives
452,Procter & Gamble,pg.com,"101,000","Vice President, Strategy & Business Development",Kirti Singh,Kirti,,,https://craft.co/procter-gamble/executives
453,Procter & Gamble,pg.com,"101,000","Vice President, Corporate Development",Andre Schulten,Andre,,,https://craft.co/procter-gamble/executives

In [118]:
df.to_csv("leads.csv")