# Imports

In [1]:
!sudo /bin/bash -c "(source /venv/bin/activate; pip install --quiet jupyterlab-vim)"
!jupyter labextension enable

In [2]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [3]:
# %%
import datetime
import logging
import os

import pandas as pd
# /venv/lib/python3.12/site-packages/gspread_pandas/spread.py:401: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)` .replace("", np.nan)
pd.set_option('future.no_silent_downcasting', True)

import helpers.hdbg as hdbg
import helpers.henv as henv
import helpers.hpandas as hpandas
import helpers.hprint as hprint
import helpers.hcache as hcache

#hcache.get_global_cache_info()
#hcache.clear_global_cache("all")

import config_root.config as cconfig

# %%
hdbg.init_logger(verbosity=logging.INFO)

_LOG = logging.getLogger(__name__)

_LOG.info("%s", henv.get_system_signature()[0])

hprint.config_notebook()

WARNING: Running in Jupyter
INFO  > cmd='/venv/lib/python3.12/site-packages/ipykernel_launcher.py -f /home/.local/share/jupyter/runtime/kernel-927b64e0-e803-401c-b8f8-72a842c96d17.json'
INFO  # Git
  branch_name='CmampTask11020_Compute_yamm_stats'
  hash='f1e22dc12'
  # Last commits:
    * f1e22dc12 GP Saggese Update                                                            (   4 hours ago) Tue Dec 31 17:55:47 2024  (HEAD -> CmampTask11020_Compute_yamm_stats, origin/CmampTask11020_Compute_yamm_stats)
    * 9e78ec83f GP Saggese Update                                                            (   5 hours ago) Tue Dec 31 16:53:51 2024
    * 27ca5e75b GP Saggese Update                                                            (   6 hours ago) Tue Dec 31 15:53:29 2024
# Machine info
  system=Linux
  node name=ce6cfb94b060
  release=6.6.22-linuxkit
  version=#1 SMP Fri Mar 29 12:21:27 UTC 2024
  machine=aarch64
  processor=aarch64
  cpu count=8
  cpu freq=None
  memory=svmem(total=8222072832, available=5933162496, percent=27.8, used=2073268224, free=2578853888, active=2444214272, inactive=2520035328, buffers=334127104, cached=3235823616, shared=7798784, slab=534360064)
  disk usage=sdiskusage(total=62671097856, used=56639660032, free=2814722048, percent=95.3)
# Packages
  python: 3.12.3
  cvxopt: 1.3.2
  cvxpy: 1.5.3
  gluonnlp: ?
  gluonts: ?
  joblib: 1.4.2
  mxnet: ?
  numpy: 2.1.3
  pandas: 2.2.3
  pyarrow: 18.0.0
  scipy: 1.14.1
  seaborn: 0.13.2
  sklearn: 1.5.2
  statsmodels: 0.14.4

In [4]:
import gspread
print(gspread.__version__)

import gspread_pandas
print(gspread_pandas.__version__)

#gspread_pandas.conf.get_config()
print(gspread_pandas.conf.get_config()["project_id"])

5.12.4
3.3.0
gspread-gp

In [7]:
#!sudo /bin/f bash -c "(source /venv/bin/activate; pip install --upgrade google-api-python-client)"

import importlib
import ck_marketing.process_automation.hyamm as hyamm
importlib.reload(hyamm)

import ck_marketing.hunterio.hunter_api as cmhuhuap
importlib.reload(cmhuhuap)

import helpers.hopenai as hopenai

# Load data

In [170]:
#normalize = False
normalize = True
contact_df = hyamm.get_data_from_GP_LIn_connections(normalize)
print("shape=", contact_df.shape)
contact_df.head(2)

INFO  Reading data from url='https://docs.google.com/spreadsheets/d/19ziUmqbPaUO73cqlJB1F9y-j1Oq98nMzo6wTmzyVnwg' sheet_name='Sheet1'
shape= (2205, 18)

  hash              origin                 timestamp first_name last_name email email_verification                            linkedin_url                                          job_title                              job_title_description company_name company_domain                               city stages restrictions industry category notes
0       GP_LIn_connections  2024-12-31T02:08:03.137Z  Graham C.      Peck                              https://linkedin.com/in/grahamcpeck                                      CFO & Partner  Co-Founder @ DealSend & Attaq Vector | Partner...     FYC Labs                  Chicago, Illinois, United States                                Design
1       GP_LIn_connections  2024-12-31T02:08:03.997Z     Justin   Fortier                           https://linkedin.com/in/justinffortier  Chief Executive Officer / Chief Technical Officer  Founder + CEO/CTO @ FYC Labs; I love creating ...     FYC Labs                 Folsom, California, United States                                Design

In [162]:
#hyamm.save_to_gsheet(df, name="connects")

In [163]:
#df.iloc[11]

In [201]:
contact_df = hyamm.clean_up_contact_df(contact_df, allow_no_emails=True)

duplicated_emails: removed 0 / 2205 = 0.00%
remove_invalid_emails: removed 0 / 2205 = 0.00%
remove_chinese_names: removed 0 / 2205 = 0.00%
remove_empty_first_names: removed 0 / 2205 = 0.00%
clean_company_names: replaced urls in company_name 0 / 2205 = 0.00%
clean_linkedin_nans: replaced nans in linkedin_url 0 / 2205 = 0.00%
clean_linkedin_emails: replaced emails in linkedin_url 0 / 2205 = 0.00%
clean_linkedin_websites: replaced urls in linkedin_url 0 / 2205 = 0.00%
clean_emails: replaced emails 0 / 2205 = 0.00%

# Enrich

In [202]:
#mode = "AssumeEmailValid"
mode = "FromScratch"
contact_df_tmp = cmhuhuap.process_enrich(contact_df, "first_name", "last_name", "company_name", mode=mode)
display(contact_df_tmp.head(2))

  0%|          | 0/2205 [00:00<?, ?it/s]

WARNING No data for 'RR' 'Consulting' at ''
WARNING No data for 'Jerry' 'Freishtat' at ''
WARNING No data for 'Pedro Elias' 'B' at 'Four Brothers'
WARNING No data for 'Martina' 'Szeto' at 'Meta'
WARNING No data for 'Alfredo' 'Fiorentino' at ''
WARNING No data for 'John' 'Glover' at 'Yahoo'
WARNING No data for 'Yulia' 'Serebryanaya' at ''
WARNING No data for 'Hao' 'Huang' at 'Meta'
WARNING No data for 'Kimberly' 'P.' at 'Gov'
WARNING No data for 'Gabriela' 'Jacques da Silva' at 'Meta'
WARNING No data for 'Chris' 'T' at 'Stealth Startup'
WARNING No data for 'Kalyan' 'Saladi' at 'Meta'
WARNING No data for 'Xin "Sean"' 'Xin' at 'Ivy Capital'
WARNING No data for 'Zizheng' 'Zhang' at ''
WARNING No data for 'Ruohan' 'Gao' at 'Meta'
WARNING No data for 'Elan' 'Moas' at ''
WARNING No data for 'Jay(Jungsub)' 'Han' at ''
WARNING No data for 'Nathan' 'H.' at 'Principal Search'
WARNING No data for 'Kristofer "Kriffy"' 'Perez' at 'Global PayTech Ventures'
WARNING No data for 'Omer Ege' 'Kara' at ''
WARNING No data for 'Karthik' 'Pattabiraman' at 'Meta'
WARNING No data for 'Tiffany' 'Tai' at ''
WARNING No data for 'Richard' 'A.' at 'Inktelligence'
WARNING No data for 'Krishna' 'Monian' at 'Meta'
WARNING No data for 'Taiting' 'Lu' at ''
WARNING No data for 'Sahil' 'Chordia' at ''
WARNING No data for 'Renato' 'Munari' at 'Poste Italiane'
WARNING No data for 'Ali' 'Jalali' at 'Meta'
WARNING No data for 'Hanne Salome' 'S' at ''
WARNING No data for 'Kayi' 'Wong' at ''
WARNING No data for 'Canyu' 'Chen' at ''
WARNING No data for 'Natalia' 'Goldin' at ''
WARNING No data for 'Francesco' 'Pane' at ''
WARNING No data for 'Sweta' 'Dantu' at ''
WARNING No data for 'Abhi' 'Chintapalli' at 'Meta'
WARNING No data for 'Sree' '.' at 'Origins | Accelerator'
WARNING No data for 'Dhanush' 'S' at 'University of Maryland'
WARNING No data for 'Xueyan' 'Geng' at ''
WARNING No data for 'Chutian' 'Ma' at ''
WARNING No data for 'Milind' 'MSV' at ''

                                  hash              origin                 timestamp first_name last_name email email_verification                         linkedin_url                     job_title                              job_title_description    company_name company_domain                            city stages restrictions industry   category notes            hunterio.email hunterio.email_verification hunterio.company_name hunterio.company_domain hunterio.linkedin_url hunterio.job_title
1040  0001a9ecb8aa1721852bcd1817e20ad4  GP_LIn_connections  2024-12-31T15:33:29.238Z     Tyrome     Smith                           https://linkedin.com/in/tyromesmith          Principal Consultant  Strategic Advisory and Consulting Services | F...  Go In Now, LLC                 Bowie, Maryland, United States                                                                   _nan_                     invalid                 _nan_               go-now.eu                 _nan_              _nan_
141   00150db4adbd30e6ea6ba6ad8dfa80e4  GP_LIn_connections  2024-12-31T02:09:50.352Z      Nitin     Anand                                https://linkedin.com/in/nda211  Director, Product Management  Leading Product & Program Management at Assura...        Assurant                   Frisco, Texas, United States                               Insurance        nitin.anand@assurant.com                       valid              Assurant            assurant.com                 _nan_              _nan_

## Update cache

In [133]:
print(hyamm.cache_stats_to_str())

  enrich:
    memory: 2205
    disk: 2205
  find_email:
    memory: 3740
    disk: 3740
  verify_email:
    memory: 4941
    disk: 4941

In [134]:
hyamm.flush_cache_to_disk()

INFO  Before:
  enrich:
    memory: 2205
    disk: 2205
  find_email:
    memory: 3740
    disk: 3740
  verify_email:
    memory: 4941
    disk: 4941
INFO  After:
  enrich:
    memory: 2205
    disk: 2205
  find_email:
    memory: 3740
    disk: 3740
  verify_email:
    memory: 4941
    disk: 4941

## Merge

In [204]:
contact_df_tmp.columns

Index(['hash', 'origin', 'timestamp', 'first_name', 'last_name', 'email', 'email_verification', 'linkedin_url', 'job_title', 'job_title_description', 'company_name', 'company_domain', 'city', 'stages', 'restrictions', 'industry', 'category', 'notes', 'hunterio.email', 'hunterio.email_verification', 'hunterio.company_name', 'hunterio.company_domain', 'hunterio.linkedin_url', 'hunterio.job_title'], dtype='object')

In [214]:
contact_df_tmp2 = cmhuhuap.merge_hunterio_values(contact_df_tmp)

In [215]:
contact_df_tmp2.head(2)

                                  hash              origin                 timestamp first_name last_name                     email email_verification                         linkedin_url                     job_title                              job_title_description    company_name company_domain                            city stages restrictions industry   category notes
1040  0001a9ecb8aa1721852bcd1817e20ad4  GP_LIn_connections  2024-12-31T15:33:29.238Z     Tyrome     Smith                     _nan_            invalid  https://linkedin.com/in/tyromesmith          Principal Consultant  Strategic Advisory and Consulting Services | F...  Go In Now, LLC      go-now.eu  Bowie, Maryland, United States
141   00150db4adbd30e6ea6ba6ad8dfa80e4  GP_LIn_connections  2024-12-31T02:09:50.352Z      Nitin     Anand  nitin.anand@assurant.com              valid       https://linkedin.com/in/nda211  Director, Product Management  Leading Product & Program Management at Assura...        Assurant   assurant.com    Frisco, Texas, United States                               Insurance

In [217]:
hyamm.save_to_gsheet(contact_df_tmp2)

https://docs.google.com/spreadsheets/d/1sVuGF_biHcmwuWRAcldNe-Rf0_7ZJsbAhL0xJdGXG-4
INFO  Saved to display_tmp

# Add emails

In [190]:
mode = "AssumeEmailValid"
#mode = "FromScratch"
contact_df_tmp3 = cmhuhuap.process_email(contact_df_tmp2, "first_name", "last_name", "company_name", mode=mode)
display(contact_df_tmp3.head(2))

  0%|          | 0/2205 [00:00<?, ?it/s]

                                  hash              origin                 timestamp first_name last_name email email_verification                         linkedin_url                     job_title                              job_title_description    company_name company_domain                            city stages restrictions industry   category notes            hunterio.email hunterio.email_verification
1040  0001a9ecb8aa1721852bcd1817e20ad4  GP_LIn_connections  2024-12-31T15:33:29.238Z     Tyrome     Smith                           https://linkedin.com/in/tyromesmith          Principal Consultant  Strategic Advisory and Consulting Services | F...  Go In Now, LLC                 Bowie, Maryland, United States                                                                   _nan_                     invalid
141   00150db4adbd30e6ea6ba6ad8dfa80e4  GP_LIn_connections  2024-12-31T02:09:50.352Z      Nitin     Anand                                https://linkedin.com/in/nda211  Director, Product Management  Leading Product & Program Management at Assura...        Assurant                   Frisco, Texas, United States                               Insurance        nitin.anand@assurant.com                       valid

# Diagnostics

In [168]:
diagnostics_df = cmhuhuap.get_diagnostic_df(contact_df_tmp)
display(diagnostics_df.head(2))

INFO  Found: col_name='email', prefix_col_name='hunterio.email'
INFO  Found: col_name='email_verification', prefix_col_name='hunterio.email_verification'
INFO  Found: col_name='company_name', prefix_col_name='hunterio.company_name'
INFO  Found: col_name='company_domain', prefix_col_name='hunterio.company_domain'
INFO  Found: col_name='linkedin_url', prefix_col_name='hunterio.linkedin_url'
INFO  Found: col_name='job_title', prefix_col_name='hunterio.job_title'

     first_name last_name email            hunterio.email              merged.email email_verification hunterio.email_verification merged.email_verification    company_name hunterio.company_name merged.company_name company_domain hunterio.company_domain merged.company_domain                         linkedin_url hunterio.linkedin_url                  merged.linkedin_url                     job_title hunterio.job_title              merged.job_title
1040     Tyrome     Smith                           _nan_                     _nan_                                        invalid                   invalid  Go In Now, LLC                 _nan_      Go In Now, LLC                              go-now.eu             go-now.eu  https://linkedin.com/in/tyromesmith                 _nan_  https://linkedin.com/in/tyromesmith          Principal Consultant              _nan_          Principal Consultant
141       Nitin     Anand        nitin.anand@assurant.com  nitin.anand@assurant.com                                          valid                     valid        Assurant              Assurant            Assurant                           assurant.com          assurant.com       https://linkedin.com/in/nda211                 _nan_       https://linkedin.com/in/nda211  Director, Product Management              _nan_  Director, Product Management

In [169]:
hyamm.save_to_gsheet(diagnostics_df, name="diagnostics_df")

https://docs.google.com/spreadsheets/d/1IW44NeF2cteWGvrC7BCHo9GTMCXDYVLrxDBFTOb3XvI
INFO  Saved to diagnostics_df

In [107]:
stats_dict = cmhuhuap.get_stats(diagnostics_df)

if False:
    import pprint
    pprint.pprint(stats_dict, sort_dicts=False)

df_tmp = cmhuhuap.get_stats_df(stats_dict)
display(df_tmp)

cmhuhuap.get_is_changed_stats(diagnostics_df)

               tokens [%] non-empty [%]          !reachable invalid   valid
email             100.00%         0.00%  100.00%      0.00%     NaN     NaN
hunterio.email      0.00%       100.00%      NaN     52.83%  47.17%  52.83%

is_changed.email 2205 / 2205 = 100.00%
is_changed.email_verification 2205 / 2205 = 100.00%
is_changed.company_name 2089 / 2205 = 94.74%
is_changed.company_domain 2205 / 2205 = 100.00%
is_changed.linkedin_url 2205 / 2205 = 100.00%
is_changed.job_title 2205 / 2205 = 100.00%

In [57]:
hyamm.save_to_gsheet(contact_df_tmp, name="gp_connects")

https://docs.google.com/spreadsheets/d/1IgpRPEt3cbUnWhjn4PBdBJtMuo9ZWb8ns8nRiZ7JjsM
INFO  Saved to gp_connects

# Categorize

In [26]:
#keyword = "Partner", "VC", "invest", "Venture", "Director
keyword = "partner"
mask = [keyword in val.lower() for val in contact_df_tmp["job_title"]]
print(hprint.perc(sum(mask), len(mask)))

keyword = "vc"
mask = [keyword in val.lower() for val in contact_df_tmp["job_title"]]
print(hprint.perc(sum(mask), len(mask)))

keyword = "invest"
mask = [keyword in val.lower() for val in contact_df_tmp["job_title"]]
print(hprint.perc(sum(mask), len(mask)))

keyword = "venture"
mask = [keyword in val.lower() for val in contact_df_tmp["job_title"]]
print(hprint.perc(sum(mask), len(mask)))

keyword = "director"
mask = [keyword in val.lower() for val in contact_df_tmp["job_title"]]
print(hprint.perc(sum(mask), len(mask)))

345 / 2205 = 15.65%
5 / 2205 = 0.23%
106 / 2205 = 4.81%
39 / 2205 = 1.77%
199 / 2205 = 9.02%

In [29]:
keyword = "partner"
mask = [keyword in val.lower() for val in contact_df_tmp["job_title"]]
print(hprint.perc(sum(mask), len(mask)))

contact_df_tmp[mask].head(5)

345 / 2205 = 15.65%

                                  hash              origin                 timestamp first_name             last_name email email_verification                                       linkedin_url                    job_title                              job_title_description            company_name company_domain                                      city stages restrictions industry                           category notes   hunterio.company_name hunterio.company_domain              hunterio.email                             hunterio.linkedin_url hunterio.job_title
1444  01ad805293f9e2fd8643b10a1fba5a41  GP_LIn_connections  2024-12-31T19:08:06.349Z    Mariano  González Vasconcelos                                       https://linkedin.com/in/marianogonvas  Founder and General Partner  MGV Capital General Partner; Mariano is the Fo...             MGV Capital                        San Antonio, Texas, United States                                Venture Capital & Private Equity                   MGV Capital          mgvcapital.com      mariano@mgvcapital.com         https://www.linkedin.com/in/marianogonvas              _nan_
345   0261b84a964a903371a8cca4fb8066ac  GP_LIn_connections  2024-12-31T02:18:53.219Z   Courtney            Leimkuhler                           https://linkedin.com/in/courtney-leimkuhler-32...             Managing Partner  Co-Founder, Springbank | ex Marsh, NYSE, Goldm...              Springbank                        New York, New York, United States                                Venture Capital & Private Equity                         _nan_         springbank.scot                       _nan_                                             _nan_              _nan_
515   03371d4c87c6bf9f25a2f517f420a679  GP_LIn_connections  2024-12-31T02:21:00.277Z    Abie J.                 Cohen                                          https://linkedin.com/in/abiejcohen             Managing Partner  Managing Partner at Centre Street Partners; ; ...  Centre Street Partners                        New York, New York, United States                                Venture Capital & Private Equity        Centre Street Partners   centrestreet.partners  abie@centrestreet.partners  https://www.linkedin.com/in/abie-j-cohen-330b0a5   Managing Partner
1414  04352f0ee88bde6412bafb40573d54ce  GP_LIn_connections  2024-12-31T19:07:44.485Z     Festus            Turlington                           https://linkedin.com/in/festus-turlington-1106...                      Partner                      Partner at Trident Digital; ;         Trident Digital                 Charlotte, North Carolina, United States                                           Investment Management                         _nan_      tridentdigital.com                       _nan_                                             _nan_              _nan_
675   044b35afc7e3c9ad79f96b74390b78ab  GP_LIn_connections  2024-12-31T02:22:59.379Z        Jon                Crosby                                 https://linkedin.com/in/jon-crosby-5a603210  Investor / Managing Partner  Growth / Development / Digital; With over 20 y...                AppTrace                           St George, Utah, United States                               Information Technology & Services                         _nan_            apptrace.com                       _nan_                                             _nan_              _nan_

In [42]:
#print("\n".join(sorted(contact_df_tmp["category"].unique())))
print(contact_df_tmp["category"].value_counts())

category
Financial Services                       490
Venture Capital & Private Equity         315
Computer Software                        288
                                         243
Higher Education                         243
Information Technology & Services        127
Management Consulting                     34
Research                                  31
Non-profit Organization Management        20
Law Practice                              18
Insurance                                 17
Government Administration                 16
Staffing & Recruiting                     15
Automotive                                15
Education Management                      15
Computer Hardware                         15
Hospital & Health Care                    14
Investment Management                     14
Semiconductors                            14
Professional Training & Coaching          13
Banking                                   11
Real Estate                               11
E-learning                                10
Biotechnology                             10
Defense & Space                           10
Marketing & Advertising                    9
Transportation/Trucking/Railroad           9
Consumer Electronics                       9
Computer & Network Security                8
Telecommunications                         8
Health, Wellness & Fitness                 7
Investment Banking                         7
Entertainment                              6
Oil & Energy                               6
Information Services                       6
Architecture & Planning                    6
Computer Games                             5
Renewables & Environment                   5
Apparel & Fashion                          5
Internet                                   4
Design                                     4
Accounting                                 4
Food & Beverages                           4
Construction                               4
Industrial Automation                      3
Luxury Goods & Jewelry                     3
Primary/Secondary Education                3
Consumer Services                          3
Mental Health Care                         3
Fine Art                                   3
Hospitality                                3
Public Relations & Communications          3
Publishing                                 3
Consumer Goods                             3
Market Research                            2
Medical Practice                           2
Pharmaceuticals                            2
Airlines/Aviation                          2
Electrical & Electronic Manufacturing      2
Think Tanks                                2
Retail                                     2
Leisure, Travel & Tourism                  2
Building Materials                         2
Events Services                            2
Government Relations                       2
Civic & Social Organization                2
Medical Device                             2
Media Production                           2
Sports                                     1
Alternative Medicine                       1
Military                                   1
Animation                                  1
Program Development                        1
Wine & Spirits                             1
Shipbuilding                               1
Writing & Editing                          1
Museums & Institutions                     1
Civil Engineering                          1
Music                                      1
Translation & Localization                 1
Food Production                            1
Utilities                                  1
Security & Investigations                  1
Glass, Ceramics & Concrete                 1
Legal Services                             1
Restaurants                                1
Mechanical Or Industrial Engineering       1
Fundraising                                1
Commercial Real Estate                     1
Aviation & Aerospace                       1
Name: count, dtype: int64

In [33]:
keyword = "Venture Capital & Private Equity"
#mask = [keyword in val.lower() for val in contact_df_tmp["category"]]
mask = contact_df_tmp["category"] == keyword
print(hprint.perc(sum(mask), len(mask)))

315 / 2205 = 14.29%

In [44]:
display(contact_df_tmp[mask].head())

                                  hash              origin                 timestamp first_name             last_name email email_verification                                       linkedin_url                    job_title                              job_title_description            company_name company_domain                               city stages restrictions industry                          category notes   hunterio.company_name hunterio.company_domain              hunterio.email                             hunterio.linkedin_url hunterio.job_title
443   0109c0cd68412821ddba894fbadb8e35  GP_LIn_connections  2024-12-31T02:20:06.797Z     Yasmin                   Gao                                           https://linkedin.com/in/yasmingao                    Investing  Investing @ Capital 49 | Forbes 30 under 30; D...              Capital 49                                     United States                               Venture Capital & Private Equity                         _nan_           capital49.com                       _nan_                                             _nan_              _nan_
1444  01ad805293f9e2fd8643b10a1fba5a41  GP_LIn_connections  2024-12-31T19:08:06.349Z    Mariano  González Vasconcelos                                       https://linkedin.com/in/marianogonvas  Founder and General Partner  MGV Capital General Partner; Mariano is the Fo...             MGV Capital                 San Antonio, Texas, United States                               Venture Capital & Private Equity                   MGV Capital          mgvcapital.com      mariano@mgvcapital.com         https://www.linkedin.com/in/marianogonvas              _nan_
345   0261b84a964a903371a8cca4fb8066ac  GP_LIn_connections  2024-12-31T02:18:53.219Z   Courtney            Leimkuhler                           https://linkedin.com/in/courtney-leimkuhler-32...             Managing Partner  Co-Founder, Springbank | ex Marsh, NYSE, Goldm...              Springbank                 New York, New York, United States                               Venture Capital & Private Equity                         _nan_         springbank.scot                       _nan_                                             _nan_              _nan_
515   03371d4c87c6bf9f25a2f517f420a679  GP_LIn_connections  2024-12-31T02:21:00.277Z    Abie J.                 Cohen                                          https://linkedin.com/in/abiejcohen             Managing Partner  Managing Partner at Centre Street Partners; ; ...  Centre Street Partners                 New York, New York, United States                               Venture Capital & Private Equity        Centre Street Partners   centrestreet.partners  abie@centrestreet.partners  https://www.linkedin.com/in/abie-j-cohen-330b0a5   Managing Partner
877   05c64f26289b44346ee658aa78d80ed2  GP_LIn_connections  2024-12-31T02:25:24.414Z     Oliver              Mitchell                                     https://linkedin.com/in/oliverbmitchell                      Partner  investor, professor, writer, robot/a.i. enthus...      ff Venture Capital                 New York, New York, United States                               Venture Capital & Private Equity            ff Venture Capital                ffvc.com    oliver.mitchell@ffvc.com                                             _nan_              _nan_

In [51]:
col_names = ["hash", "first_name", "last_name", "email", "job_title", "linkedin_url", "company_name"]
df = contact_df_tmp[mask][col_names]
df = df.sort_values(by="company_name")

hyamm.save_to_gsheet(df, name="gp_vc_connects")

https://docs.google.com/spreadsheets/d/1kwzhsgbqCFMx83y5MFt2aRPSm94oTiAHem5B-UpiMes
INFO  Saved to gp_vc_connects