In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [5]:
# %%
import datetime
import logging
import os

import pandas as pd
# /venv/lib/python3.12/site-packages/gspread_pandas/spread.py:401: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)` .replace("", np.nan)
pd.set_option('future.no_silent_downcasting', True)

import helpers.hdbg as hdbg
import helpers.henv as henv
import helpers.hio as hio
import helpers.hpandas as hpandas
import helpers.hprint as hprint
import helpers.hcache as hcache

#hcache.get_global_cache_info()
#hcache.clear_global_cache("all")

import config_root.config as cconfig

# %%
hdbg.init_logger(verbosity=logging.INFO)

_LOG = logging.getLogger(__name__)

_LOG.info("%s", henv.get_system_signature()[0])

hprint.config_notebook()

WARNING: Logger already initialized: skipping
INFO  # Git
  branch_name='CmampTask11020_Compute_yamm_stats'
  hash='d2293f44a'
  # Last commits:
    * d2293f44a GP Saggese Update                                                            (    4 days ago) Wed Jan 22 00:04:59 2025  (HEAD -> CmampTask11020_Compute_yamm_stats, origin/CmampTask11020_Compute_yamm_stats)
    * 5404856e0 GP Saggese Update                                                            (    4 days ago) Tue Jan 21 19:42:57 2025
    * 9685fb48f GP Saggese Lint                                                              (    6 days ago) Sun Jan 19 23:49:38 2025
# Machine info
  system=Linux
  node name=9b21dea71c71
  release=6.10.14-linuxkit
  version=#1 SMP Fri Nov 29 17:22:03 UTC 2024
  machine=aarch64
  processor=aarch64
  cpu count=8
  cpu freq=None
  memory=svmem(total=8218251264, available=5728026624, percent=30.3, used=2271641600, free=701063168, active=2949562368, inactive=3359866880, buffers=1318604800, cached=3926941696, shared=10747904, slab=1052217344)
  disk usage=sdiskusage(total=62671097856, used=30821908480, free=28632473600, percent=51.8)
# Packages
  python: 3.12.3
  cvxopt: 1.3.2
  cvxpy: 1.5.3
  gluonnlp: ?
  gluonts: ?
  joblib: 1.4.2
  mxnet: ?
  numpy: 2.1.3
  pandas: 2.2.3
  pyarrow: 18.0.0
  scipy: 1.14.1
  seaborn: 0.13.2
  sklearn: 1.5.2
  statsmodels: 0.14.4

In [3]:
import gspread
print(gspread.__version__)

import gspread_pandas
print(gspread_pandas.__version__)

#gspread_pandas.conf.get_config()
print(gspread_pandas.conf.get_config()["project_id"])

5.12.4
3.3.0
gspread-gp

In [24]:
lines = hio.from_file("../../family_offices.txt")
lines = lines.split("\n")

# Ensure data is divisible by 6 for clean processing
# if len(lines) % 7 != 0:
#     raise ValueError("The data does not align properly into rows of 6.")

# Split into groups of 6
data = [lines[i:i+6] for i in range(0, len(lines), 6)]

# Create DataFrame
df = pd.DataFrame(data, columns=['Family Office', 'Name', 'Email', 'City', 'State', 'Website'])

df

                                        Family Office                 Name                                 Email               City     State                                  Website
0                                       Family Office                 Name                                 Email               City     State                                  Website
1                   Fleming Family & Partners Limited        Ahmet Feridun              ahmet.feridun@ffandp.com             London         –                                        -
2                                      Stamos Capital         Ron Marryott           rmarryott@stamoscapital.com                  –        CA     https://www.stamoscapital.com/about/
3                                      TAG Associates       John Pantowich               jpantowich@tagassoc.com           New York        NY                                        –
4                                HOLBEIN PARTNERS LLP        ANDERE RODGER     andere.rodger@holbeinpartners.com             London         –          http://www.holbeinpartners.com/
5                                      ICONIQ Capital       Vid Mahansaria                 vid@iconiqcapital.com      San Francisco        CA            http://www.iconiqcapital.com/
6                                      Vedra Partners   JOACHIM GOTTSCHALK  joachim.gottschalk@vedrapartners.com           Lausanne         –            http://www.vedrapartners.com/
7                                      Ash Crest Corp           Tony Brita                     tony@ashcrest.com         Fort Wayne        IN                                        –
8                                 Flynn Family Office           Evan Jehle                     ejehle@ffollc.com                  –         –                    flynnfamilyoffice.com
9                        Keep Bermuda Beautiful (KBB)         Susan Harvey                            smh@ibl.bm           Hamilton  Hamilton                        http://www.kbb.bm
10                      Uinta Investment Partners LLC          Gavin James              gjames@uintapartners.com                  –         –  http://www.uintainvestmentpartners.com/
11                                    Perspecta Trust      STEPHEN J. TALL              stall@perspectatrust.com            Hampton        NH              https://perspectatrust.com/
12                          Habif Arogeti & Wynne LLP          Edward Deck                    ed.deck@hawcpa.com            Atlanta        GA                          info@hawcpa.com
13                            Piedmont Partners Group        Stephen Leist     shleist@piedmontpartnersgroup.com           Piedmont        CA            www.piedmontpartnersgroup.com
14                          Baldwin Family Office LLC  Susan Berry Kohlhas                skohlhas@baldwinim.com  West Conshohocken        PA                                        –
15                             Omega Asset Management             M Garcia             mgarcia@omega-capital.com             Madrid         –                http://www.omega-am.co.uk
16                             Pitcairn Family Office     Ronna Gyllenhaal             r.gyllenhaal@pitcairn.com         Jenkintown        PA                 http://www.pitcairn.com/
17                           Sandy Cove Advisors, LLC        Robert Reilly         rreilly@sandycoveadvisors.com            Hingham        MA        http://www.sandycoveadvisors.com/
18                     Legacy Capital Management Inc.           Jason Bell          theteam@legacycapitalinc.com          Roseville        CA                                        –
19  Paragon Advisors, Inc. (Falmouth Investment Co...       Brian C. Clark            bclark@paragonadvisors.net     Shaker Heights        OH                  www.paragonadvisors.net
20                       Colin&Cie. Wealth Management      BERND KLINGBEIL          bernd.klingbeil@colin-cie.lu        Schuttrange         –                http://www.colin-cie.com/
21                Turim Investimentos - Family Office        Sergio Marini                     turim@turimbr.com     Rio de Janeiro         –                   http://www.turimbr.com
22                              Daintree Advisors LLC      Mary M. Shahian         mshahian@daintreeadvisors.com             Boston        MA         http://www.daintreeadvisors.com/
23                                     Atlantic Trust          Lester Duke               lduke@atlantictrust.com            Atlanta        GA                                        –
24                                         Briar Hall        Dulcie Truitt                 dtruitt@briarhall.com            Chicago        IL                        www.briarhall.com
25                                          Onvest Oy     RISTO TORNIVAARA            risto.tornivaara@onvest.fi           Helsinki         –                    http://www.onvest.fi/
26                                                                    None                                  None               None      None                                     None

In [16]:
len(lines) % 7

4

In [12]:
df

                              Family Office                                               Name                Email                                  City              State   Website
0                             Family Office                                               Name                Email                                  City              State   Website
1         Fleming Family & Partners Limited                                               Open        Ahmet Feridun              ahmet.feridun@ffandp.com             London         –
2                                         –                                     Stamos Capital         Ron Marryott           rmarryott@stamoscapital.com                  –        CA
3      https://www.stamoscapital.com/about/                                     TAG Associates       John Pantowich               jpantowich@tagassoc.com           New York        NY
4                                         –                               HOLBEIN PARTNERS LLP        ANDERE RODGER     andere.rodger@holbeinpartners.com             London         –
5           http://www.holbeinpartners.com/                                     ICONIQ Capital       Vid Mahansaria                 vid@iconiqcapital.com      San Francisco        CA
6             http://www.iconiqcapital.com/                                     Vedra Partners   JOACHIM GOTTSCHALK  joachim.gottschalk@vedrapartners.com           Lausanne         –
7             http://www.vedrapartners.com/                                     Ash Crest Corp           Tony Brita                     tony@ashcrest.com         Fort Wayne        IN
8                                         –                                Flynn Family Office           Evan Jehle                     ejehle@ffollc.com                  –         –
9                     flynnfamilyoffice.com                       Keep Bermuda Beautiful (KBB)         Susan Harvey                            smh@ibl.bm           Hamilton  Hamilton
10                        http://www.kbb.bm                      Uinta Investment Partners LLC          Gavin James              gjames@uintapartners.com                  –         –
11  http://www.uintainvestmentpartners.com/                                    Perspecta Trust      STEPHEN J. TALL              stall@perspectatrust.com            Hampton        NH
12              https://perspectatrust.com/                          Habif Arogeti & Wynne LLP          Edward Deck                    ed.deck@hawcpa.com            Atlanta        GA
13                          info@hawcpa.com                            Piedmont Partners Group        Stephen Leist     shleist@piedmontpartnersgroup.com           Piedmont        CA
14            www.piedmontpartnersgroup.com                          Baldwin Family Office LLC  Susan Berry Kohlhas                skohlhas@baldwinim.com  West Conshohocken        PA
15                                        –                             Omega Asset Management             M Garcia             mgarcia@omega-capital.com             Madrid         –
16                http://www.omega-am.co.uk                             Pitcairn Family Office     Ronna Gyllenhaal             r.gyllenhaal@pitcairn.com         Jenkintown        PA
17                 http://www.pitcairn.com/                           Sandy Cove Advisors, LLC        Robert Reilly         rreilly@sandycoveadvisors.com            Hingham        MA
18        http://www.sandycoveadvisors.com/                     Legacy Capital Management Inc.           Jason Bell          theteam@legacycapitalinc.com          Roseville        CA
19                                        –  Paragon Advisors, Inc. (Falmouth Investment Co...       Brian C. Clark            bclark@paragonadvisors.net     Shaker Heights        OH
20                  www.paragonadvisors.net                       Colin&Cie. Wealth Management      BERND KLINGBEIL          bernd.klingbeil@colin-cie.lu        Schuttrange         –
21                http://www.colin-cie.com/                Turim Investimentos - Family Office        Sergio Marini                     turim@turimbr.com     Rio de Janeiro         –
22                   http://www.turimbr.com                              Daintree Advisors LLC      Mary M. Shahian         mshahian@daintreeadvisors.com             Boston        MA
23         http://www.daintreeadvisors.com/                                     Atlantic Trust          Lester Duke               lduke@atlantictrust.com            Atlanta        GA
24                                        –                                         Briar Hall        Dulcie Truitt                 dtruitt@briarhall.com            Chicago        IL
25                        www.briarhall.com                                          Onvest Oy     RISTO TORNIVAARA            risto.tornivaara@onvest.fi           Helsinki         –
26                    http://www.onvest.fi/                                                                    None                                  None               None      None