CONTENTS:

In [21]:
#!sudo /bin/bash -c "(source /venv/bin/activate; pip install --upgrade google-api-python-client)"

In [53]:
import importlib
import os

import ck_marketing.hunterio.hunter_api as cmhuhuap
import helpers.hgoogle_file_api as hgofiapi

importlib.reload(hgofiapi)
importlib.reload(cmhuhuap)

In [5]:
hunter_api = os.environ.get("HUNTER_API_KEY")
drop_api = os.environ.get("DROPCONTACT_API_KEY")

In [6]:
creds = hgofiapi.get_credentials()

In [7]:
link = "https://docs.google.com/spreadsheets/d/1o07XnIArFdIjz0jTZuyPkldxBczhQhMywdF9Xe9kNmo/edit?gid=1379255156#gid=1379255156"
df = hgofiapi.read_google_file(link, "chatgpt_extract", credentials=creds)

In [8]:
df.head()

,Name,Job Title,Company,Company Size,Source Link,email
0,Brandon Tseng,Co-Founder & CEO,Shield AI,"<10,000 employees",https://www.linkedin.com/in/brandon-tseng-5b3b...,
1,Ryan Tseng,Co-Founder & COO,Shield AI,"<10,000 employees",https://www.linkedin.com/in/ryantseng/,
2,Shane O'Hara,Chief Financial Officer,Shield AI,"<10,000 employees",https://www.linkedin.com/in/shane-ohara-6b139b2/,
3,Craig O'Neill,Chief Technology Officer,Shield AI,"<10,000 employees",https://www.linkedin.com/in/craig-oneill/,
4,Jennifer Dyer,Chief Strategy Officer,Shield AI,"<10,000 employees",https://www.linkedin.com/in/jennifer-dyer-8a7b...,

In [9]:
df[["firstName", "lastName"]] = df["Name"].str.split(" ", n=1, expand=True)

In [10]:
df.head()

,Name,Job Title,Company,Company Size,Source Link,email,firstName,lastName
0,Brandon Tseng,Co-Founder & CEO,Shield AI,"<10,000 employees",https://www.linkedin.com/in/brandon-tseng-5b3b...,,Brandon,Tseng
1,Ryan Tseng,Co-Founder & COO,Shield AI,"<10,000 employees",https://www.linkedin.com/in/ryantseng/,,Ryan,Tseng
2,Shane O'Hara,Chief Financial Officer,Shield AI,"<10,000 employees",https://www.linkedin.com/in/shane-ohara-6b139b2/,,Shane,O'Hara
3,Craig O'Neill,Chief Technology Officer,Shield AI,"<10,000 employees",https://www.linkedin.com/in/craig-oneill/,,Craig,O'Neill
4,Jennifer Dyer,Chief Strategy Officer,Shield AI,"<10,000 employees",https://www.linkedin.com/in/jennifer-dyer-8a7b...,,Jennifer,Dyer

In [11]:
df.shape

(1143, 8)

In [12]:
df_test = df.iloc[50:60]

In [13]:
df_test

,Name,Job Title,Company,Company Size,Source Link,email,firstName,lastName
50,Michael D. Smith,CFO,SpotHopper,"<10,000 employees",https://www.linkedin.com/in/michael-smith-654321,,Michael,D. Smith
51,Sarah B. Johnson,COO,SpotHopper,"<10,000 employees",https://www.linkedin.com/in/sarah-johnson-789012,,Sarah,B. Johnson
52,Lucas R. Thompson,Chief Strategy Officer,SpotHopper,"<10,000 employees",https://www.linkedin.com/in/lucas-thompson-345678,,Lucas,R. Thompson
53,Emma J. Davis,VP of Corporate Development,SpotHopper,"<10,000 employees",https://www.linkedin.com/in/emma-davis-901234,,Emma,J. Davis
54,Saurabh Sinha,Co-Founder & CEO,Cricket.com,"<10,000 employees",https://www.linkedin.com/in/saurabhsinha,,Saurabh,Sinha
55,Ravi Bhatia,Co-Founder & CTO,Cricket.com,"<10,000 employees",https://www.linkedin.com/in/ravibhatia,,Ravi,Bhatia
56,Vaibhav Sinha,Co-Founder & COO,Cricket.com,"<10,000 employees",https://www.linkedin.com/in/vaibhavsinha,,Vaibhav,Sinha
57,Amit Kumar,VP of Strategy & Business Development,Cricket.com,"<10,000 employees",https://www.linkedin.com/in/amittkumar,,Amit,Kumar
58,Synthesia CEO,CEO,Synthesia,"<10,000 employees",https://www.linkedin.com/in/synthesia-ceo,,Synthesia,CEO
59,Synthesia CFO,CFO,Synthesia,"<10,000 employees",https://www.linkedin.com/in/synthesia-cfo,,Synthesia,CFO

In [14]:
acc_info = cmhuhuap.get_account_info()
acc_info

{'searches': {'used': 1199, 'available': 5000, 'over_quota': 0},
 'verifications': {'used': 0, 'available': 10000, 'over_quota': 0},
 'reset_date': '2025-03-25'}

In [55]:
res = cmhuhuap.process_email(
    df_test, "firstName", "lastName", "Company", is_company=True
)

  0%|          | 0/10 [00:00<?, ?it/s]

cache {"('Michael', 'D. Smith', 'SpotHopper', True)": '_nan_', "('Sarah', 'B. Johnson', 'SpotHopper', True)": '_nan_', "('Lucas', 'R. Thompson', 'SpotHopper', True)": '_nan_', "('Emma', 'J. Davis', 'SpotHopper', True)": 'emma@spothopperapp.com', "('Saurabh', 'Sinha', 'Cricket.com', True)": '_nan_', "('Ravi', 'Bhatia', 'Cricket.com', True)": '_nan_', "('Vaibhav', 'Sinha', 'Cricket.com', True)": '_nan_', "('Amit', 'Kumar', 'Cricket.com', True)": '_nan_', "('Synthesia', 'CEO', 'Synthesia', True)": 'synthesia@synthesia.io', "('Synthesia', 'CFO', 'Synthesia', True)": 'synthesia@synthesia.io'}
cache {"('Michael', 'D. Smith', 'SpotHopper', True)": '_nan_', "('Sarah', 'B. Johnson', 'SpotHopper', True)": '_nan_', "('Lucas', 'R. Thompson', 'SpotHopper', True)": '_nan_', "('Emma', 'J. Davis', 'SpotHopper', True)": 'emma@spothopperapp.com', "('Saurabh', 'Sinha', 'Cricket.com', True)": '_nan_', "('Ravi', 'Bhatia', 'Cricket.com', True)": '_nan_', "('Vaibhav', 'Sinha', 'Cricket.com', True)": '_nan_', "('Amit', 'Kumar', 'Cricket.com', True)": '_nan_', "('Synthesia', 'CEO', 'Synthesia', True)": 'synthesia@synthesia.io', "('Synthesia', 'CFO', 'Synthesia', True)": 'synthesia@synthesia.io'}
cache {"('Michael', 'D. Smith', 'SpotHopper', True)": '_nan_', "('Sarah', 'B. Johnson', 'SpotHopper', True)": '_nan_', "('Lucas', 'R. Thompson', 'SpotHopper', True)": '_nan_', "('Emma', 'J. Davis', 'SpotHopper', True)": 'emma@spothopperapp.com', "('Saurabh', 'Sinha', 'Cricket.com', True)": '_nan_', "('Ravi', 'Bhatia', 'Cricket.com', True)": '_nan_', "('Vaibhav', 'Sinha', 'Cricket.com', True)": '_nan_', "('Amit', 'Kumar', 'Cricket.com', True)": '_nan_', "('Synthesia', 'CEO', 'Synthesia', True)": 'synthesia@synthesia.io', "('Synthesia', 'CFO', 'Synthesia', True)": 'synthesia@synthesia.io'}
cache {"('Michael', 'D. Smith', 'SpotHopper', True)": '_nan_', "('Sarah', 'B. Johnson', 'SpotHopper', True)": '_nan_', "('Lucas', 'R. Thompson', 'SpotHopper', True)": '_nan_', "('Emma', 'J. Davis', 'SpotHopper', True)": 'emma@spothopperapp.com', "('Saurabh', 'Sinha', 'Cricket.com', True)": '_nan_', "('Ravi', 'Bhatia', 'Cricket.com', True)": '_nan_', "('Vaibhav', 'Sinha', 'Cricket.com', True)": '_nan_', "('Amit', 'Kumar', 'Cricket.com', True)": '_nan_', "('Synthesia', 'CEO', 'Synthesia', True)": 'synthesia@synthesia.io', "('Synthesia', 'CFO', 'Synthesia', True)": 'synthesia@synthesia.io'}
cache {"('Michael', 'D. Smith', 'SpotHopper', True)": '_nan_', "('Sarah', 'B. Johnson', 'SpotHopper', True)": '_nan_', "('Lucas', 'R. Thompson', 'SpotHopper', True)": '_nan_', "('Emma', 'J. Davis', 'SpotHopper', True)": 'emma@spothopperapp.com', "('Saurabh', 'Sinha', 'Cricket.com', True)": '_nan_', "('Ravi', 'Bhatia', 'Cricket.com', True)": '_nan_', "('Vaibhav', 'Sinha', 'Cricket.com', True)": '_nan_', "('Amit', 'Kumar', 'Cricket.com', True)": '_nan_', "('Synthesia', 'CEO', 'Synthesia', True)": 'synthesia@synthesia.io', "('Synthesia', 'CFO', 'Synthesia', True)": 'synthesia@synthesia.io'}
cache {"('Michael', 'D. Smith', 'SpotHopper', True)": '_nan_', "('Sarah', 'B. Johnson', 'SpotHopper', True)": '_nan_', "('Lucas', 'R. Thompson', 'SpotHopper', True)": '_nan_', "('Emma', 'J. Davis', 'SpotHopper', True)": 'emma@spothopperapp.com', "('Saurabh', 'Sinha', 'Cricket.com', True)": '_nan_', "('Ravi', 'Bhatia', 'Cricket.com', True)": '_nan_', "('Vaibhav', 'Sinha', 'Cricket.com', True)": '_nan_', "('Amit', 'Kumar', 'Cricket.com', True)": '_nan_', "('Synthesia', 'CEO', 'Synthesia', True)": 'synthesia@synthesia.io', "('Synthesia', 'CFO', 'Synthesia', True)": 'synthesia@synthesia.io'}
cache {"('Michael', 'D. Smith', 'SpotHopper', True)": '_nan_', "('Sarah', 'B. Johnson', 'SpotHopper', True)": '_nan_', "('Lucas', 'R. Thompson', 'SpotHopper', True)": '_nan_', "('Emma', 'J. Davis', 'SpotHopper', True)": 'emma@spothopperapp.com', "('Saurabh', 'Sinha', 'Cricket.com', True)": '_nan_', "('Ravi', 'Bhatia', 'Cricket.com', True)": '_nan_', "('Vaibhav', 'Sinha', 'Cricket.com', True)": '_nan_', "('Amit', 'Kumar', 'Cricket.com', True)": '_nan_', "('Synthesia', 'CEO', 'Synthesia', True)": 'synthesia@synthesia.io', "('Synthesia', 'CFO', 'Synthesia', True)": 'synthesia@synthesia.io'}
cache {"('Michael', 'D. Smith', 'SpotHopper', True)": '_nan_', "('Sarah', 'B. Johnson', 'SpotHopper', True)": '_nan_', "('Lucas', 'R. Thompson', 'SpotHopper', True)": '_nan_', "('Emma', 'J. Davis', 'SpotHopper', True)": 'emma@spothopperapp.com', "('Saurabh', 'Sinha', 'Cricket.com', True)": '_nan_', "('Ravi', 'Bhatia', 'Cricket.com', True)": '_nan_', "('Vaibhav', 'Sinha', 'Cricket.com', True)": '_nan_', "('Amit', 'Kumar', 'Cricket.com', True)": '_nan_', "('Synthesia', 'CEO', 'Synthesia', True)": 'synthesia@synthesia.io', "('Synthesia', 'CFO', 'Synthesia', True)": 'synthesia@synthesia.io'}
cache {"('Michael', 'D. Smith', 'SpotHopper', True)": '_nan_', "('Sarah', 'B. Johnson', 'SpotHopper', True)": '_nan_', "('Lucas', 'R. Thompson', 'SpotHopper', True)": '_nan_', "('Emma', 'J. Davis', 'SpotHopper', True)": 'emma@spothopperapp.com', "('Saurabh', 'Sinha', 'Cricket.com', True)": '_nan_', "('Ravi', 'Bhatia', 'Cricket.com', True)": '_nan_', "('Vaibhav', 'Sinha', 'Cricket.com', True)": '_nan_', "('Amit', 'Kumar', 'Cricket.com', True)": '_nan_', "('Synthesia', 'CEO', 'Synthesia', True)": 'synthesia@synthesia.io', "('Synthesia', 'CFO', 'Synthesia', True)": 'synthesia@synthesia.io'}
cache {"('Michael', 'D. Smith', 'SpotHopper', True)": '_nan_', "('Sarah', 'B. Johnson', 'SpotHopper', True)": '_nan_', "('Lucas', 'R. Thompson', 'SpotHopper', True)": '_nan_', "('Emma', 'J. Davis', 'SpotHopper', True)": 'emma@spothopperapp.com', "('Saurabh', 'Sinha', 'Cricket.com', True)": '_nan_', "('Ravi', 'Bhatia', 'Cricket.com', True)": '_nan_', "('Vaibhav', 'Sinha', 'Cricket.com', True)": '_nan_', "('Amit', 'Kumar', 'Cricket.com', True)": '_nan_', "('Synthesia', 'CEO', 'Synthesia', True)": 'synthesia@synthesia.io', "('Synthesia', 'CFO', 'Synthesia', True)": 'synthesia@synthesia.io'}

In [56]:
res

,Name,Job Title,Company,Company Size,Source Link,email,firstName,lastName,hunterio.email,hunterio.email_verification
50,Michael D. Smith,CFO,SpotHopper,"<10,000 employees",https://www.linkedin.com/in/michael-smith-654321,,Michael,D. Smith,_nan_,invalid
51,Sarah B. Johnson,COO,SpotHopper,"<10,000 employees",https://www.linkedin.com/in/sarah-johnson-789012,,Sarah,B. Johnson,_nan_,invalid
52,Lucas R. Thompson,Chief Strategy Officer,SpotHopper,"<10,000 employees",https://www.linkedin.com/in/lucas-thompson-345678,,Lucas,R. Thompson,_nan_,invalid
53,Emma J. Davis,VP of Corporate Development,SpotHopper,"<10,000 employees",https://www.linkedin.com/in/emma-davis-901234,,Emma,J. Davis,emma@spothopperapp.com,valid
54,Saurabh Sinha,Co-Founder & CEO,Cricket.com,"<10,000 employees",https://www.linkedin.com/in/saurabhsinha,,Saurabh,Sinha,_nan_,invalid
55,Ravi Bhatia,Co-Founder & CTO,Cricket.com,"<10,000 employees",https://www.linkedin.com/in/ravibhatia,,Ravi,Bhatia,_nan_,invalid
56,Vaibhav Sinha,Co-Founder & COO,Cricket.com,"<10,000 employees",https://www.linkedin.com/in/vaibhavsinha,,Vaibhav,Sinha,_nan_,invalid
57,Amit Kumar,VP of Strategy & Business Development,Cricket.com,"<10,000 employees",https://www.linkedin.com/in/amittkumar,,Amit,Kumar,_nan_,invalid
58,Synthesia CEO,CEO,Synthesia,"<10,000 employees",https://www.linkedin.com/in/synthesia-ceo,,Synthesia,CEO,synthesia@synthesia.io,valid
59,Synthesia CFO,CFO,Synthesia,"<10,000 employees",https://www.linkedin.com/in/synthesia-cfo,,Synthesia,CFO,synthesia@synthesia.io,valid